#!/bin/bash --login
########## SBATCH Lines for Resource Request ##########
 
#SBATCH --time=120:00:00             # limit of wall clock time - how long the job will run (same as -t)
#SBATCH --nodes=1                 # number of different nodes - could be an exact number or a range of nodes (same as -N)
#SBATCH --ntasks=1                  # number of tasks - how many tasks (nodes) that you require (same as -n)
#SBATCH --cpus-per-task=4           # number of CPUs (or cores) per task (same as -c)
#SBATCH --mem-per-cpu=32G            # memory required per allocated CPU (or core) - amount of memory (in bytes)
#SBATCH --job-name proteinortho_pipeline      # you can give your job a name for easier identification (same as -J)
#SBATCH --mail-user=elijahlowe@gmail.com
#SBATCH --mail-type=ALL
 
########## Command Lines to Run ##########

module load screed
module load khmer
module load oases
module load velvet
module load FASTX

mocuG_sra='SRR1501181 SRR1501179 SRR1501177'
moccG_sra='SRR1501175 SRR1501173 SRR1501171'
moxiG_sra='SRR1501096 SRR1501095 SRR1491616'

mocuT_sra='SRR1197522 SRR1197965 SRR1197972' 
moccT_sra='SRR1197985 SRR1197986 SRR1199259 SRR1199268 SRR1199464'
hybT_sra='SRR1198346 SRR1198337 SRR1198321'
cd $SCRATCH/mol_paper/

for sra in $mocuT_sra $moccT_sra $hybT_sra;do wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/${sra:0:6}/00${sra:9:10}/$sra/*;done
for i in SRR*gz;do zcat $i | sed 's/SRR.*\ H/H/g' > ${i/.gz/};done
#for sra in $all_sra;do wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/${sra:0:6}/00${sra:9:10}/$sra/*;done
