#!/bin/bash -login

#PBS -l walltime=168:00:00,nodes=1:ppn=10,mem=32gb
#PBS -N mocu_transdecoder
#PBS -A ged
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load transdecoder/3.0.0
module load blast+
module load HMMER/3.1b2

cd $SCRATCH/mol_paper/
#TransDecoder.LongOrfs -t mocu_trinity_genes.fasta
blastp -query mocu_trinity_genes.fasta.transdecoder_dir/longest_orfs.pep -db /mnt/research/common-data/Bio/Uniref90/uniref90.fasta -max_target_seqs 1 -outfmt 6 -evalue 1e-5 -num_threads 10 > mocu_gene_blastp.outfmt6
hmmscan --cpu 8 --domtblout mocu_gene_pfam.domtblout Pfam-A.hmm mocu_trinity_genes.fasta.transdecoder_dir/longest_orfs.pep
TransDecoder.Predict -t mocu_trinity_genes.fasta --retain_pfam_hits mocu_gene_pfam.domtblout --retain_blastp_hits mocu_gene_blastp.outfmt6

qstat -f ${PBS_JOBID}

