#!/bin/bash -login
#PBS -l walltime=48:00:00,nodes=1:ppn=2,mem=64gb
#PBS -o mocu.x.ciona.$PBS_JOBID
#PBS -q biocluster-6
#PBS -j oe
#PBS -m abe
#PBS -M elowe3@gatech.edu

module load gcc/4.6.2
module load boost/1.53.0
module load python/2.7
module load ncbi_blast/2.2.29

cd scratch

blastx -db KH.KHGene.2012.Met.protein.fasta -query mocu_GG_supertrans.fasta.transdecoder.mRNA -out mocu.x.ciona.output -outfmt 6 -evalue 0.01 -max_target_seqs 20


qstat -f ${PBS_JOBID}

