#!/bin/bash -login

#PBS -l walltime=68:00:00,nodes=1:ppn=8,mem=128gb
#PBS -N mocc_hisat2
#PBS -A ged
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load hisat2
module load SAMTools/1.5
module load Java/1.8.0_31

cd $SCRATCH/mol_paper/reads

ln -sf ~/genomes/mocc.redundan.fa .

hisat2-build mocc.redundan.fa mocc.redundan

hisat2 -p 8 --rg-id=Mocu_3.1hpf --rg SM:Mocu_3hpf --rg PL:ILLUMINA --rg PU:Mocu_3.1hpf_L001 -x mocc.redundan --rna-strandness RF -1 SRR1197985_1.new_fastq -2 SRR1197985_2.new_fastq -S SRR1197985.sam
hisat2 -p 8 --rg-id=Mocu_3hpf --rg SM:Mocc_3hpf --rg PL:ILLUMINA --rg PU:Mocc_3hpf_L001 -x mocc.redundan --rna-strandness RF -1 SRR1197986_1.new_fastq -2 SRR1197986_2.new_fastq -S SRR1197986.sam
hisat2 -p 8 --rg-id=Mocu_5hpf --rg SM:Mocc_5hpf --rg PL:ILLUMINA --rg PU:Mocc_5hpf_L001 -x mocc.redundan --rna-strandness RF -1 SRR1199259_1.new_fastq -2 SRR1199259_2.new_fastq -S SRR1199259.sam
hisat2 -p 8 --rg-id=Mocu_6hpf --rg SM:Mocc_6hpf --rg PL:ILLUMINA --rg PU:Mocc_6hpf_L001 -x mocc.redundan --rna-strandness RF -1 SRR1199268_1.new_fastq -2 SRR1199268_2.new_fastq -S SRR1199268.sam
hisat2 -p 8 --rg-id=Mocu_4hpf --rg SM:Mocc_4hpf --rg PL:ILLUMINA --rg PU:Mocc_4hpf_L001 -x mocc.redundan --rna-strandness RF -1 SRR1199464_1.new_fastq -2 SRR1199464_2.new_fastq -S SRR1199464.sam

samtools sort -@ 8 -o SRR1197985.bam SRR1197985.sam
samtools sort -@ 8 -o SRR1197986.bam SRR1197986.sam
samtools sort -@ 8 -o SRR1199259.bam SRR1199259.sam
samtools sort -@ 8 -o SRR1199268.bam SRR1199268.sam
samtools sort -@ 8 -o SRR1199464.bam SRR1199464.sam

java -Xmx112g -jar ~/picard/picard.jar MergeSamFiles OUTPUT=mocu.bam INPUT=SRR1197985.bam INPUT=SRR1197986.bam INPUT=SRR1199259.bam INPUT=SRR1199268.bam INPUT=SRR1199464.bam

qstat -f ${PBS_JOBID}